name = "bty-website"
main = ".open-next/worker.js"
compatibility_date = "2026-02-14"
compatibility_flags = ["nodejs_compat", "nodejs_compat_v2", "nodejs_compat_populate_process_env", "global_fetch_strictly_public"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "bty-website"
